name: Build Base Image (arm64)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: macos/linux-5.9.13
        key: cache-arm64-2
        restore-keys: cache-arm64-1
    - name: Build
      run: cd macos && sudo ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- ./build.sh && tar czf virt.tar.gz vmlinuz vda.img
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: macos/virt.tar.gz
