name: Build Base Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          macos/linux-5.9.13
          macos/musl-1.2.1
          macos/busybox-1.32.0
        key: cache-1
        restore-keys: |
          ${{ runner.os }}-linux-5.9.13
    - name: Build
      run: cd macos && sudo ./build.sh && tar czf virt.tar.gz vmlinuz vda.img
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: virt.tar.gz
