name: Build Base Image (x86_64)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2
      with:
        path: macos/linux
        key: cache-x86_64-7
        restore-keys: cache-x86_64-0
    - name: Build
      run: cd macos && docker run -v $PWD:/root/macos ubuntu:20.10 sh -c 'cd ~/macos && ARCH=x86_64 ./build.sh' && sudo ARCH=x86_64 ./buildImage.sh && tar czf virt.tar.gz vmlinuz vda.img
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: macos/virt.tar.gz
