name: Build Base Image
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: macos/linux
        key: cache-${{matrix.arch}}-${{ hashFiles('macos/linux.version') }}
    - run: cd macos && docker run -v $PWD:/root/macos ubuntu:20.10 sh -c 'cd ~/macos && ARCH=${{matrix.arch}} ./build.sh' && sudo ARCH=${{matrix.arch}} ./buildImage.sh && tar czf virt.tar.gz vmlinuz vda.img
    - uses: actions/upload-artifact@v2
      with:
        name: virt-${{matrix.arch}}
        path: macos/virt.tar.gz
