name: Build JDK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: adoptium/build-jdk@v1
      with:
        javaToBuild: jdk11u
        impl: hotspot
    - uses: actions/upload-artifact@v2
      with:
        path: build/src/build/linux-x86_64-normal-server-release/images/OpenJDK.tar.gz
