name: Build Tool
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_13.0_beta.app
    - name: Build with Xcode
      run: cd macos/virt && xcodebuild
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: macos/virt/build/Release/virt
